name: Build on Linux
run-name: ${{ github.actor }} is building on Linux🚀
on: [workflow_dispatch]
jobs:
  Build-on-Linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to exec code on the runner."
      - name: List files in github.workspace
        run: |
          ls ${{ github.workspace }}
      - name: List files in extern
        run: |
          ls ${{ github.workspace }}/extern
      - name: List files in extern/libzedmd
        run: |
          ls ${{ github.workspace }}/extern/libzedmd
      - name: list
        working-directory: extern/libzedmd/
        run: ls
      - name: Prerequisite for libzedmd
        working-directory: extern/libzedmd/
        run: platforms/linux/x64/external.sh
      - name: Configure CMake
        working-directory: extern/libzedmd/
        run: |
          cmake -DPLATFORM=linux
          -DARCH=x64
          -DCMAKE_BUILD_TYPE=Release
          -B build
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_COMPILER=gcc
      - name: Build
        working-directory: extern/libzedmd/
        run: cmake --build build
      - name: Build extend
        working-directory: ${{ github.workspace }}
        run: |
          g++ -O3 -Wall -shared -std=c++11 -fPIC $(python3-config --includes) -Iextern/pybind11/include
          -Iextern/libzedmd/src -Lextern/libzedmd/build extending.cpp
          -o build/extending$(python3-config --extension-suffix)  -ldl -lpthread -lutil -lzedmd -lserialport


